INSERT INTO `USERS_TABLE` ( `LOGIN`, `EMAIL`, `PASSWORD`,`ROLE`)
VALUES ( 'teste', 'teste', '12345','ADMIN');

INSERT INTO `USERS_TABLE` ( `LOGIN`, `EMAIL`, `PASSWORD`,`ROLE`)
VALUES ( 'testee', 'testee', '12345','USER');
